### PR TITLE
Add filter dropdowns for Cards (type/rarity/color/cost)

### LINKED ISSUE #20: Filter Cards by Type
We need to figure out how to filter cards by type (skill, attack, power, etc) to help with "bottled" relic cards and for possible future issues we run into.

The [cards](https://github.com/zuelong/save-the-spire/blob/master/src/components/CardsJSON.js) file currently does not have these defined, so it will require a closer look at the games actual code to figure out exactly how this is working and if it's possible to implement.

### PR DESCRIPTION
**Pull request by saltyeyes**
Updated CardsJSON.js with several relevant attributes for each card (took a bit of digging!) which should help to resolve #20 😄 
Added four dropdowns under the search box with filters for Type, Rarity, Color and Cost.

### CODE REVIEW

**Comment by saltyeyes** [comment]
Updated the bottled relic modal, should now only show valid cards or a relevant error message

**Comment by ntower** [comment]
👍 

I thought about filtering the bottled relic modal when i added it, but didn't have the metadata to do so. Incidentally, the game doesn't check the types except when you acquire the relic, so even if you pair it with a card of the wrong type, it will happily put that card into your opening hand.

**Comment by zuelong** [comment]
Awesome!  I'm going to go ahead and merge this.  I need to update the height of the scrollbox on the right side of the screen isnt off the page, but it looks great.

Awesome work with the CardsJSON as well :)

**Comment by zuelong** [comment]
So after giving this another round of testing ( in production, because i missed it when I tested it before the merge :D ).  The filtering logic seems a little off.  However, I'm not rolling anything back because it's late here at the moment and the functionality still works somewhat.  Worst case scenario is that it isn't used.

Anyway, the problem appears to be with how the number filter works.  Instead of comparing `["1"] includes "1"` it's checking for `[" 1"] includes "1"` in the `filterCard` method.   I can probably squeeze a PR in tomorrow if one of you doesnt get to it first.

Again, awesome work and thanks for the feature :)

**Comment by zuelong** [comment]
Finally decided on just trimming the object keys on comparison to preserve order: [link](https://github.com/zuelong/save-the-spire/commit/ff3f92bace417b65d479d1bea6fda3ecf90136d2)

**Pull request merged**
